server.port=8081
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:apppassword}
spring.datasource.hikari.initialization-fail-timeout=0
spring.sql.init.mode=always
