apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:

      # -------------------
      # INIT CONTAINER (WAIT FOR POSTGRES)
      # -------------------
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          command:
            - sh
            - -c
            - >
              until nc -z "$DB_HOST" "$DB_PORT";
              do echo "waiting for postgres"; sleep 2; done

      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret

          ports:
            - containerPort: 8081

          # -------------------
          # STARTUP PROBE (IMPORTANT FIX)
          # prevents crash loops during boot
          # -------------------
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            failureThreshold: 30
            periodSeconds: 10

          # -------------------
          # LIVENESS PROBE (IS APP ALIVE?)
          # -------------------
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5

          # -------------------
          # READINESS PROBE (CAN SERVE TRAFFIC?)
          # -------------------
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5